version: "3.8"

services:
    redis:
        image: redis:7-alpine
        container_name: webshop-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: redis-server --appendonly yes
        restart: unless-stopped
        networks:
            - webshop-network

volumes:
    redis_data:

networks:
    webshop-network:
        driver: bridge
